# Generated by Django 5.0.6 on 2024-08-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salehistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
